// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: collectionx.proto

package collection_core_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderTypeProto int32

const (
	OrderTypeProto_ORDER_TYPE_NONE OrderTypeProto = 0
	OrderTypeProto_ORDER_TYPE_ASC  OrderTypeProto = 1
	OrderTypeProto_ORDER_TYPE_DESC OrderTypeProto = 2
)

// Enum value maps for OrderTypeProto.
var (
	OrderTypeProto_name = map[int32]string{
		0: "ORDER_TYPE_NONE",
		1: "ORDER_TYPE_ASC",
		2: "ORDER_TYPE_DESC",
	}
	OrderTypeProto_value = map[string]int32{
		"ORDER_TYPE_NONE": 0,
		"ORDER_TYPE_ASC":  1,
		"ORDER_TYPE_DESC": 2,
	}
)

func (x OrderTypeProto) Enum() *OrderTypeProto {
	p := new(OrderTypeProto)
	*p = x
	return p
}

func (x OrderTypeProto) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderTypeProto) Descriptor() protoreflect.EnumDescriptor {
	return file_collectionx_proto_enumTypes[0].Descriptor()
}

func (OrderTypeProto) Type() protoreflect.EnumType {
	return &file_collectionx_proto_enumTypes[0]
}

func (x OrderTypeProto) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderTypeProto.Descriptor instead.
func (OrderTypeProto) EnumDescriptor() ([]byte, []int) {
	return file_collectionx_proto_rawDescGZIP(), []int{0}
}

type PayloadProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RootCollection string           `protobuf:"bytes,1,opt,name=root_collection,json=rootCollection,proto3" json:"root_collection,omitempty"`
	RootDocument   string           `protobuf:"bytes,2,opt,name=root_document,json=rootDocument,proto3" json:"root_document,omitempty"`
	Data           *structpb.Struct `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Limit          int32            `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	IsPagination   bool             `protobuf:"varint,5,opt,name=is_pagination,json=isPagination,proto3" json:"is_pagination,omitempty"`
	IsDelete       bool             `protobuf:"varint,6,opt,name=is_delete,json=isDelete,proto3" json:"is_delete,omitempty"`
	Path           []*PathProto     `protobuf:"bytes,7,rep,name=path,proto3" json:"path,omitempty"`
	Query          *QueryProto      `protobuf:"bytes,8,opt,name=query,proto3" json:"query,omitempty"`
	Pagination     *PaginationProto `protobuf:"bytes,9,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (x *PayloadProto) Reset() {
	*x = PayloadProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collectionx_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayloadProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadProto) ProtoMessage() {}

func (x *PayloadProto) ProtoReflect() protoreflect.Message {
	mi := &file_collectionx_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadProto.ProtoReflect.Descriptor instead.
func (*PayloadProto) Descriptor() ([]byte, []int) {
	return file_collectionx_proto_rawDescGZIP(), []int{0}
}

func (x *PayloadProto) GetRootCollection() string {
	if x != nil {
		return x.RootCollection
	}
	return ""
}

func (x *PayloadProto) GetRootDocument() string {
	if x != nil {
		return x.RootDocument
	}
	return ""
}

func (x *PayloadProto) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PayloadProto) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PayloadProto) GetIsPagination() bool {
	if x != nil {
		return x.IsPagination
	}
	return false
}

func (x *PayloadProto) GetIsDelete() bool {
	if x != nil {
		return x.IsDelete
	}
	return false
}

func (x *PayloadProto) GetPath() []*PathProto {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *PayloadProto) GetQuery() *QueryProto {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *PayloadProto) GetPagination() *PaginationProto {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type PathProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CollectionId string `protobuf:"bytes,1,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	DocumentId   string `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	NewDocument  bool   `protobuf:"varint,3,opt,name=new_document,json=newDocument,proto3" json:"new_document,omitempty"`
}

func (x *PathProto) Reset() {
	*x = PathProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collectionx_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PathProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathProto) ProtoMessage() {}

func (x *PathProto) ProtoReflect() protoreflect.Message {
	mi := &file_collectionx_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathProto.ProtoReflect.Descriptor instead.
func (*PathProto) Descriptor() ([]byte, []int) {
	return file_collectionx_proto_rawDescGZIP(), []int{1}
}

func (x *PathProto) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *PathProto) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *PathProto) GetNewDocument() bool {
	if x != nil {
		return x.NewDocument
	}
	return false
}

type StandardAPIProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  string           `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Entity  string           `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`
	State   string           `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Message string           `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Meta    *MetaProto       `protobuf:"bytes,5,opt,name=meta,proto3,oneof" json:"meta,omitempty"`
	Errors  *structpb.Struct `protobuf:"bytes,6,opt,name=errors,proto3,oneof" json:"errors,omitempty"`
}

func (x *StandardAPIProto) Reset() {
	*x = StandardAPIProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collectionx_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StandardAPIProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StandardAPIProto) ProtoMessage() {}

func (x *StandardAPIProto) ProtoReflect() protoreflect.Message {
	mi := &file_collectionx_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StandardAPIProto.ProtoReflect.Descriptor instead.
func (*StandardAPIProto) Descriptor() ([]byte, []int) {
	return file_collectionx_proto_rawDescGZIP(), []int{2}
}

func (x *StandardAPIProto) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StandardAPIProto) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *StandardAPIProto) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *StandardAPIProto) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StandardAPIProto) GetMeta() *MetaProto {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *StandardAPIProto) GetErrors() *structpb.Struct {
	if x != nil {
		return x.Errors
	}
	return nil
}

type DateRangeProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Start *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
}

func (x *DateRangeProto) Reset() {
	*x = DateRangeProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collectionx_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DateRangeProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateRangeProto) ProtoMessage() {}

func (x *DateRangeProto) ProtoReflect() protoreflect.Message {
	mi := &file_collectionx_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateRangeProto.ProtoReflect.Descriptor instead.
func (*DateRangeProto) Descriptor() ([]byte, []int) {
	return file_collectionx_proto_rawDescGZIP(), []int{3}
}

func (x *DateRangeProto) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *DateRangeProto) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *DateRangeProto) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

type FilterProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	By  string `protobuf:"bytes,1,opt,name=by,proto3" json:"by,omitempty"`
	Op  string `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`
	Val []byte `protobuf:"bytes,3,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *FilterProto) Reset() {
	*x = FilterProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collectionx_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilterProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterProto) ProtoMessage() {}

func (x *FilterProto) ProtoReflect() protoreflect.Message {
	mi := &file_collectionx_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterProto.ProtoReflect.Descriptor instead.
func (*FilterProto) Descriptor() ([]byte, []int) {
	return file_collectionx_proto_rawDescGZIP(), []int{4}
}

func (x *FilterProto) GetBy() string {
	if x != nil {
		return x.By
	}
	return ""
}

func (x *FilterProto) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *FilterProto) GetVal() []byte {
	if x != nil {
		return x.Val
	}
	return nil
}

type SortProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderBy   string         `protobuf:"bytes,1,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	OrderType OrderTypeProto `protobuf:"varint,2,opt,name=order_type,json=orderType,proto3,enum=collectionx.OrderTypeProto" json:"order_type,omitempty"`
}

func (x *SortProto) Reset() {
	*x = SortProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collectionx_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SortProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortProto) ProtoMessage() {}

func (x *SortProto) ProtoReflect() protoreflect.Message {
	mi := &file_collectionx_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortProto.ProtoReflect.Descriptor instead.
func (*SortProto) Descriptor() ([]byte, []int) {
	return file_collectionx_proto_rawDescGZIP(), []int{5}
}

func (x *SortProto) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *SortProto) GetOrderType() OrderTypeProto {
	if x != nil {
		return x.OrderType
	}
	return OrderTypeProto_ORDER_TYPE_NONE
}

type QueryProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sort      []*SortProto    `protobuf:"bytes,1,rep,name=sort,proto3" json:"sort,omitempty"`
	Filter    []*FilterProto  `protobuf:"bytes,2,rep,name=filter,proto3" json:"filter,omitempty"`
	DateRange *DateRangeProto `protobuf:"bytes,3,opt,name=date_range,json=dateRange,proto3,oneof" json:"date_range,omitempty"`
}

func (x *QueryProto) Reset() {
	*x = QueryProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collectionx_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryProto) ProtoMessage() {}

func (x *QueryProto) ProtoReflect() protoreflect.Message {
	mi := &file_collectionx_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryProto.ProtoReflect.Descriptor instead.
func (*QueryProto) Descriptor() ([]byte, []int) {
	return file_collectionx_proto_rawDescGZIP(), []int{6}
}

func (x *QueryProto) GetSort() []*SortProto {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *QueryProto) GetFilter() []*FilterProto {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *QueryProto) GetDateRange() *DateRangeProto {
	if x != nil {
		return x.DateRange
	}
	return nil
}

type PaginationProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *PaginationProto) Reset() {
	*x = PaginationProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collectionx_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaginationProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationProto) ProtoMessage() {}

func (x *PaginationProto) ProtoReflect() protoreflect.Message {
	mi := &file_collectionx_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationProto.ProtoReflect.Descriptor instead.
func (*PaginationProto) Descriptor() ([]byte, []int) {
	return file_collectionx_proto_rawDescGZIP(), []int{7}
}

func (x *PaginationProto) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type MetaProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page    int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PerPage int32 `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	Size    int32 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Total   int32 `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *MetaProto) Reset() {
	*x = MetaProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collectionx_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetaProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaProto) ProtoMessage() {}

func (x *MetaProto) ProtoReflect() protoreflect.Message {
	mi := &file_collectionx_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaProto.ProtoReflect.Descriptor instead.
func (*MetaProto) Descriptor() ([]byte, []int) {
	return file_collectionx_proto_rawDescGZIP(), []int{8}
}

func (x *MetaProto) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *MetaProto) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *MetaProto) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *MetaProto) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type MetadataProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page  int32       `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Query *QueryProto `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *MetadataProto) Reset() {
	*x = MetadataProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collectionx_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetadataProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataProto) ProtoMessage() {}

func (x *MetadataProto) ProtoReflect() protoreflect.Message {
	mi := &file_collectionx_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataProto.ProtoReflect.Descriptor instead.
func (*MetadataProto) Descriptor() ([]byte, []int) {
	return file_collectionx_proto_rawDescGZIP(), []int{9}
}

func (x *MetadataProto) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *MetadataProto) GetQuery() *QueryProto {
	if x != nil {
		return x.Query
	}
	return nil
}

type RetriveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Api  *StandardAPIProto `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Data []byte            `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *RetriveResponse) Reset() {
	*x = RetriveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collectionx_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetriveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetriveResponse) ProtoMessage() {}

func (x *RetriveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collectionx_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetriveResponse.ProtoReflect.Descriptor instead.
func (*RetriveResponse) Descriptor() ([]byte, []int) {
	return file_collectionx_proto_rawDescGZIP(), []int{10}
}

func (x *RetriveResponse) GetApi() *StandardAPIProto {
	if x != nil {
		return x.Api
	}
	return nil
}

func (x *RetriveResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type RetriveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload *PayloadProto `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *RetriveRequest) Reset() {
	*x = RetriveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collectionx_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetriveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetriveRequest) ProtoMessage() {}

func (x *RetriveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collectionx_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetriveRequest.ProtoReflect.Descriptor instead.
func (*RetriveRequest) Descriptor() ([]byte, []int) {
	return file_collectionx_proto_rawDescGZIP(), []int{11}
}

func (x *RetriveRequest) GetPayload() *PayloadProto {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_collectionx_proto protoreflect.FileDescriptor

var file_collectionx_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x78, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x78,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xfa, 0x02, 0x0a, 0x0c, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x27, 0x0a, 0x0f, 0x72, 0x6f, 0x6f, 0x74, 0x5f, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x72, 0x6f, 0x6f, 0x74, 0x43,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x6f, 0x6f,
	0x74, 0x5f, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x72, 0x6f, 0x6f, 0x74, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x2b,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x12, 0x23, 0x0a, 0x0d, 0x69, 0x73, 0x5f, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x69, 0x73, 0x50, 0x61, 0x67, 0x69,
	0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x64, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x07, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x78, 0x2e,
	0x50, 0x61, 0x74, 0x68, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12,
	0x2d, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x78, 0x2e, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x3c,
	0x0a, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x78,
	0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x52, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x74, 0x0a, 0x09,
	0x50, 0x61, 0x74, 0x68, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1f,
	0x0a, 0x0b, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x21, 0x0a, 0x0c, 0x6e, 0x65, 0x77, 0x5f, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x6e, 0x65, 0x77, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x22, 0xed, 0x01, 0x0a, 0x10, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x41,
	0x50, 0x49, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2f, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x78, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52,
	0x04, 0x6d, 0x65, 0x74, 0x61, 0x88, 0x01, 0x01, 0x12, 0x34, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x48, 0x01, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x88, 0x01, 0x01, 0x42, 0x07,
	0x0a, 0x05, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x73, 0x22, 0x86, 0x01, 0x0a, 0x0e, 0x44, 0x61, 0x74, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x30, 0x0a, 0x05, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x2c, 0x0a,
	0x03, 0x65, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x22, 0x3f, 0x0a, 0x0b, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x62, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x62, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x70,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6f, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x61,
	0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x22, 0x62, 0x0a, 0x09,
	0x53, 0x6f, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x5f, 0x62, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x42, 0x79, 0x12, 0x3a, 0x0a, 0x0a, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x78, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65,
	0x22, 0xba, 0x01, 0x0a, 0x0a, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x2a, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x78, 0x2e, 0x53, 0x6f, 0x72, 0x74,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x12, 0x30, 0x0a, 0x06, 0x66,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x6f,
	0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x78, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x3f, 0x0a,
	0x0a, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x78, 0x2e,
	0x44, 0x61, 0x74, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00,
	0x52, 0x09, 0x64, 0x61, 0x74, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0d,
	0x0a, 0x0b, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x22, 0x25, 0x0a,
	0x0f, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x22, 0x64, 0x0a, 0x09, 0x4d, 0x65, 0x74, 0x61, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x65, 0x72, 0x50, 0x61, 0x67, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x73, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x52, 0x0a, 0x0d, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12,
	0x2d, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x78, 0x2e, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x56,
	0x0a, 0x0f, 0x52, 0x65, 0x74, 0x72, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2f, 0x0a, 0x03, 0x61, 0x70, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d,
	0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x78, 0x2e, 0x53, 0x74, 0x61,
	0x6e, 0x64, 0x61, 0x72, 0x64, 0x41, 0x50, 0x49, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x03, 0x61,
	0x70, 0x69, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x45, 0x0a, 0x0e, 0x52, 0x65, 0x74, 0x72, 0x69, 0x76,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x63, 0x6f, 0x6c, 0x6c,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x78, 0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2a, 0x4e, 0x0a,
	0x0e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x13, 0x0a, 0x0f, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4e, 0x4f,
	0x4e, 0x45, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x41, 0x53, 0x43, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x4f, 0x52, 0x44, 0x45,
	0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x44, 0x45, 0x53, 0x43, 0x10, 0x02, 0x32, 0x59, 0x0a,
	0x11, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x44, 0x0a, 0x07, 0x52, 0x65, 0x74, 0x72, 0x69, 0x76, 0x65, 0x12, 0x1b, 0x2e,
	0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x78, 0x2e, 0x52, 0x65, 0x74, 0x72,
	0x69, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x63, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x78, 0x2e, 0x52, 0x65, 0x74, 0x72, 0x69, 0x76, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x26, 0x5a, 0x24, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x79, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f,
	0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x78, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_collectionx_proto_rawDescOnce sync.Once
	file_collectionx_proto_rawDescData = file_collectionx_proto_rawDesc
)

func file_collectionx_proto_rawDescGZIP() []byte {
	file_collectionx_proto_rawDescOnce.Do(func() {
		file_collectionx_proto_rawDescData = protoimpl.X.CompressGZIP(file_collectionx_proto_rawDescData)
	})
	return file_collectionx_proto_rawDescData
}

var file_collectionx_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_collectionx_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_collectionx_proto_goTypes = []interface{}{
	(OrderTypeProto)(0),           // 0: collectionx.OrderTypeProto
	(*PayloadProto)(nil),          // 1: collectionx.PayloadProto
	(*PathProto)(nil),             // 2: collectionx.PathProto
	(*StandardAPIProto)(nil),      // 3: collectionx.StandardAPIProto
	(*DateRangeProto)(nil),        // 4: collectionx.DateRangeProto
	(*FilterProto)(nil),           // 5: collectionx.FilterProto
	(*SortProto)(nil),             // 6: collectionx.SortProto
	(*QueryProto)(nil),            // 7: collectionx.QueryProto
	(*PaginationProto)(nil),       // 8: collectionx.PaginationProto
	(*MetaProto)(nil),             // 9: collectionx.MetaProto
	(*MetadataProto)(nil),         // 10: collectionx.MetadataProto
	(*RetriveResponse)(nil),       // 11: collectionx.RetriveResponse
	(*RetriveRequest)(nil),        // 12: collectionx.RetriveRequest
	(*structpb.Struct)(nil),       // 13: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
}
var file_collectionx_proto_depIdxs = []int32{
	13, // 0: collectionx.PayloadProto.data:type_name -> google.protobuf.Struct
	2,  // 1: collectionx.PayloadProto.path:type_name -> collectionx.PathProto
	7,  // 2: collectionx.PayloadProto.query:type_name -> collectionx.QueryProto
	8,  // 3: collectionx.PayloadProto.pagination:type_name -> collectionx.PaginationProto
	9,  // 4: collectionx.StandardAPIProto.meta:type_name -> collectionx.MetaProto
	13, // 5: collectionx.StandardAPIProto.errors:type_name -> google.protobuf.Struct
	14, // 6: collectionx.DateRangeProto.start:type_name -> google.protobuf.Timestamp
	14, // 7: collectionx.DateRangeProto.end:type_name -> google.protobuf.Timestamp
	0,  // 8: collectionx.SortProto.order_type:type_name -> collectionx.OrderTypeProto
	6,  // 9: collectionx.QueryProto.sort:type_name -> collectionx.SortProto
	5,  // 10: collectionx.QueryProto.filter:type_name -> collectionx.FilterProto
	4,  // 11: collectionx.QueryProto.date_range:type_name -> collectionx.DateRangeProto
	7,  // 12: collectionx.MetadataProto.query:type_name -> collectionx.QueryProto
	3,  // 13: collectionx.RetriveResponse.api:type_name -> collectionx.StandardAPIProto
	1,  // 14: collectionx.RetriveRequest.payload:type_name -> collectionx.PayloadProto
	12, // 15: collectionx.ServiceCollection.Retrive:input_type -> collectionx.RetriveRequest
	11, // 16: collectionx.ServiceCollection.Retrive:output_type -> collectionx.RetriveResponse
	16, // [16:17] is the sub-list for method output_type
	15, // [15:16] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_collectionx_proto_init() }
func file_collectionx_proto_init() {
	if File_collectionx_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_collectionx_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayloadProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collectionx_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PathProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collectionx_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StandardAPIProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collectionx_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DateRangeProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collectionx_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilterProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collectionx_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SortProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collectionx_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collectionx_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaginationProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collectionx_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetaProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collectionx_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetadataProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collectionx_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetriveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collectionx_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetriveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_collectionx_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_collectionx_proto_msgTypes[6].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_collectionx_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_collectionx_proto_goTypes,
		DependencyIndexes: file_collectionx_proto_depIdxs,
		EnumInfos:         file_collectionx_proto_enumTypes,
		MessageInfos:      file_collectionx_proto_msgTypes,
	}.Build()
	File_collectionx_proto = out.File
	file_collectionx_proto_rawDesc = nil
	file_collectionx_proto_goTypes = nil
	file_collectionx_proto_depIdxs = nil
}
